<a href="https://colab.research.google.com/github/20d170002/SoC-Final-project/blob/main/Phase_1_Python_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_list=[1,2,3]
import numpy as np
arr=np.array(my_list)
arr
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat) #notice set of braces
print(np.arange(0,10))
print(np.arange(0,11,2)) #third arg is step size, all even terms upto 10 will get printed


[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


In [ ]:
print(np.zeros(3)), print(np.zeros((2,3))) #2X3 matrix

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


(None, None)

In [ ]:
import numpy as np
np.ones(4)
np.ones((3,4)) #rows columns


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
print(np.linspace(0,5,100))
np.eye(4) #to make identity matrix 2D matrix


[0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
 0.3030303  0.35353535 0.4040404  0.45454545 0.50505051 0.55555556
 0.60606061 0.65656566 0.70707071 0.75757576 0.80808081 0.85858586
 0.90909091 0.95959596 1.01010101 1.06060606 1.11111111 1.16161616
 1.21212121 1.26262626 1.31313131 1.36363636 1.41414141 1.46464646
 1.51515152 1.56565657 1.61616162 1.66666667 1.71717172 1.76767677
 1.81818182 1.86868687 1.91919192 1.96969697 2.02020202 2.07070707
 2.12121212 2.17171717 2.22222222 2.27272727 2.32323232 2.37373737
 2.42424242 2.47474747 2.52525253 2.57575758 2.62626263 2.67676768
 2.72727273 2.77777778 2.82828283 2.87878788 2.92929293 2.97979798
 3.03030303 3.08080808 3.13131313 3.18181818 3.23232323 3.28282828
 3.33333333 3.38383838 3.43434343 3.48484848 3.53535354 3.58585859
 3.63636364 3.68686869 3.73737374 3.78787879 3.83838384 3.88888889
 3.93939394 3.98989899 4.04040404 4.09090909 4.14141414 4.19191919
 4.24242424 4.29292929 4.34343434 4.39393939 4.44444444 4.4949

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(5) #picks random no.s in 0 to 1

array([0.76262262, 0.49184615, 0.68359416, 0.27668191, 0.55514257])

In [ ]:
np.random.rand(5,5) #to make 2d array pass 2 arg (0,1)
np.random.randn(4,4)



array([[ 0.50444082, -1.19859682, -0.24571477, -0.98277404],
       [-0.15482936,  0.86450726, -0.64812405, -0.09698145],
       [-0.12345629,  0.58868069,  0.67614528, -0.12414377],
       [-1.70298403,  0.70596784, -0.22894861,  0.59225616]])

In [ ]:
np.random.randint(1,100) #selects randomly an integer from given range lowest inclusive highest exclusive
np.random.randint(1,100,10) # 3rd arg= no. of integers we want



In [ ]:
arr = np.arange(25)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr = np.random.randint(0,50,10)
ranarr

array([48, 20,  0, 33, 20, 38, 39, 19, 30,  2])

In [ ]:
arr.reshape(5,5) #forms 5x5 array. flags an error if less/more elements than required for matrrix
#arr.reshape(4,4)=error
ranarr.max()
ranarr.min()
ranarr.argmax()
ranarr.argmin()


2

In [ ]:
arr.shape #o/p means 1d array

(25,)

In [ ]:
arr=arr.reshape(5,5)
arr
arr.shape
arr.dtype

dtype('int64')

In [ ]:
from numpy.random import randint
randint(2,6)


3

In [ ]:
import numpy as np
arr = np.arange(0,11)
arr
arr[8] #return the value at that index
arr[1:5] #returns values from index 1 to 4. 
arr[0:5]
arr[:6]
arr[5:] #starts from index 5 upto end
arr[0:5]=100
arr
arr=np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr= arr[0:6]

slice_of_arr
slice_of_arr [:]= 99  #gets all the elements
slice_of_arr
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy= arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
#now change values of elements in arr_copy
arr_copy[:] = 100
arr_copy


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
#check arr #arr_copy is the copy of arr, the changes in copy do not reflect in arr. while changes in slice does
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]]) #2d array means 2 sq brackets
print(arr_2d)
arr_2d[2][1]
arr_2d[2,1] #they both are same



[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


40

In [ ]:
arr_2d[:2, 1:] #the top right corner matrix

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d[:2]


array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
arr = np.arange(1,11)
arr
bool_arr = arr > 5
bool_arr


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr] #returm array with elements which evaluate to true

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr>5]


array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr<3]

array([1, 2])

In [ ]:
arr_2d=np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [ ]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [ ]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [ ]:
arr/arr #look 0/0 gives nan not a number

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [ ]:
np.max(arr)


10

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [ ]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])