In [3]:
import cv2
import os
import numpy as np
from PIL import Image
import pickle
BASE_DIR = ('./OpenCV-Python-Series-master/src')
image_dir = os.path.join(BASE_DIR, 'images')

face_cascade = cv2.CascadeClassifier('/Users/aadyapipersenia/Documents/SOC/OpenCV-Python-Series-master/src/cascades/data/haarcascade_frontalface_alt2.xml')
recognizer = cv2.face.LBPHFaceRecognizer_create()
#print(image_dir)

current_id = 0
label_ids = {}
y_labels = []
x_train = []

for root, dirs, files in os.walk(image_dir):
    for file in files:
        if file.endswith('png') or file.endswith('jpg'):
            path = os.path.join(root,file)
            label = os.path.basename(os.path.dirname(path)).replace(" ","-").lower()
            
            print(label,path)
            if not label in label_ids:
                label_ids[label] = current_id
                current_id += 1
            
            id_ = label_ids[label]
            print(label_ids)
            #y_label.append(label) #some number
        
            #x_train.append(path) #verify this image, turn into numpy array, convert to GRAY
            pil_image = Image.open(path).convert("L") #grayscale
            size = (550,550)
            final_image = pil_image.resize(size,Image.ANTIALIAS)
            
            
            image_array = np.array(final_image,"uint8")
            print(image_array)
            faces = face_cascade.detectMultiScale(image_array,scaleFactor = 1.5,minNeighbors = 5 )
            for(x,y,w,h) in faces:
                print(x,y,w,h)
                roi = image_array[y:y+h, x:x+w]
                x_train.append(roi)
                y_labels.append(id_)
                
with open('labels.pickle','wb') as f:
    pickle.dump(label_ids,f)
    
recognizer.train(x_train, np.array(y_labels))
recognizer.save('trainer.yml')
            

emilia-clarke ./OpenCV-Python-Series-master/src/images/emilia-clarke/4.jpg
{'emilia-clarke': 0}
[[ 19  19  21 ... 215 213 212]
 [ 20  19  21 ... 216 215 213]
 [ 21  21  21 ... 218 217 215]
 ...
 [142 128 111 ... 192 185 185]
 [142 130 117 ... 186 179 177]
 [141 130 121 ... 183 176 174]]
emilia-clarke ./OpenCV-Python-Series-master/src/images/emilia-clarke/5.jpg
{'emilia-clarke': 0}
[[ 70  57  66 ... 159 157 157]
 [ 70  58  66 ... 159 158 158]
 [ 71  58  65 ... 160 159 160]
 ...
 [ 61  75  70 ... 138 139 139]
 [ 59  74  68 ... 138 139 139]
 [ 59  74  68 ... 138 139 139]]
emilia-clarke ./OpenCV-Python-Series-master/src/images/emilia-clarke/6.jpg
{'emilia-clarke': 0}
[[110 110 110 ... 106 106 106]
 [110 110 110 ... 106 106 106]
 [110 110 110 ... 106 106 106]
 ...
 [115 116 117 ... 202 202 202]
 [116 117 118 ... 202 202 202]
 [117 117 118 ... 202 202 202]]
emilia-clarke ./OpenCV-Python-Series-master/src/images/emilia-clarke/2.jpg
{'emilia-clarke': 0}
[[51 51 51 ... 53 53 53]
 [51 51 51 ... 

[[147 147 144 ... 124 123 125]
 [145 146 146 ... 123 123 124]
 [145 145 146 ... 119 119 118]
 ...
 [137 138 137 ... 140 139 139]
 [137 138 137 ... 139 139 139]
 [137 138 138 ... 139 139 138]]
328 180 152 152
justin ./OpenCV-Python-Series-master/src/images/justin/4.png
{'emilia-clarke': 0, 'nikolaj-coster-waldau': 1, 'peter-dinklage': 2, 'kit-harington': 3, 'fun': 4, 'justin': 5}
[[204 203 204 ... 157 157 157]
 [203 202 203 ... 158 158 158]
 [203 201 203 ... 157 158 158]
 ...
 [193 194 194 ...  78  77  76]
 [193 195 194 ...  79  74  75]
 [196 193 193 ...  80  77  79]]
128 123 342 342
justin ./OpenCV-Python-Series-master/src/images/justin/5.png
{'emilia-clarke': 0, 'nikolaj-coster-waldau': 1, 'peter-dinklage': 2, 'kit-harington': 3, 'fun': 4, 'justin': 5}
[[225 225 224 ... 225 225 225]
 [225 224 223 ... 225 225 225]
 [225 225 224 ... 225 225 225]
 ...
 [216 209 198 ...  71  72  73]
 [193 196 202 ...  69  70  71]
 [198 206 216 ...  68  70  71]]
149 161 342 342
justin ./OpenCV-Python-Serie